
version: '3.7'
services:
        neo4j_container:
                image: neo4j:latest
                restart: on-failure
                ports:
                        - 7474:7474
                        - 7687:7687
                volumes:
                        - ./conf:/conf
                        - ./data:/data
                        - ./import:/import
                        - ./los:/logs
                        - ./plugins:/plugins
                environment:
                        - NEO4J_dbms_security_procedures_unrestricted=apoc$
                        - NEO4J_dbms_security_allow__csv__import__from__fi$
                        - NEO4J_apoc_export_file_enabled=true
                        - NEO4J_apoc_import_file_enabled=true
                        - NEO4J_apoc_import_file_use__neo4j_config=true
                        - NEO4J_dbms_allow__upgrade=true
