version: "3.9"
services:
        elasticsearch:
                image: elasticsearch:7.14.2
                container_name: elasticsearch
                environment:
                        - discovery.type=single-node
                volumes:
                        - data01:/usr/share/elasticsearch/data
                ports:
                        - 9200:9200
                        - 9300:9300
        kibana:
                image: kibana:7.14.2
                container_name: kibana
                ports:
                        - "80:5601"
                environment:
                        ELASTICSEARCH_URL: http://elasticsearch:9200
                        ELASTICSEARCH_HOSTS: http://elasticsearch:9200
                depends_on:
                        - elasticsearch
volumes:
        data01:
